---
- hosts: webservers
  become: true
  become_user: root
  vars:
    filename: "{{filename}}"
    src_path: "{{src_path}}"
  tasks:
  - name: Install httpd package
    yum: name=httpd state=installed
  - name: Copy files from source to destination
    copy: src={{src_path}}/{{filename}} dest=/var/www/html
  - name: Start HTTPD services
    service: name=httpd state=started
