apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      name: addressbook-pod
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook-container
        image: iamdevopstrainer/addressbook:6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
