apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-dep
spec:
  revisionHistoryLimit: 5
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      name: demoapp-pod
      labels:
        app: demoapp
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - name: demoapp-container
        image: iamdevopstrainer/httpd:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
