apiVersion: v1
kind: Pod
metadata:
  name: addressbook-pod
  labels:
    app: addressbook
spec:
  containers:
  - name: addressbook-container
    image: iamdevopstrainer/addressbook:5
    ports:
    - containerPort: 8080
