apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample
spec:
  containers:
  - name: sample-cont
    image: iamdevopstrainer/addressbook:5
    ports:
    - containerPort: 8080
  - name: nginx-cont
    image: nginx
    ports:
    - containerPort: 80
