apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
spec:
  ports:
  - port: 8989
    nodePort: 31001
    # 30000-32767
    targetPort: 8080
    protocol: TCP
  selector:
    app: addressbook
  type: NodePort
